config/routes.rb
Rails.application.routes.draw do

  root 'mains#index'

  get '/search' => 'search#index'

  post '/posts/addcomment' =>'posts#addcomment'

  resources :moods
  resources :posts

  devise_for :users
    devise_scope :user do
    get '/users/:id' => 'users/registrations#show'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 1}
  validates :content, presence: true, length: {minimum: 5}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.joins(:user).select("posts.id AS posts_id, posts.title, posts.category, users.id AS users_id, users.username").order("posts.id DESC")
  end

  def create
    @new_post = Post.new(new_post)
    if @new_post.save
      redirect_to posts_path
    else
      redirect_to :back
      flash[:alert] = "All Fields Are Required!"
    end
  end

  def new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.where(post_id: params[:id]).order("comments.id DESC")
  end

  def destroy
    @post_delete = Post.find(params[:id]).delete
    redirect_to posts_path
  end

  def addcomment
    @new_comment = Comment.new(new_comment)
    if @new_comment.save
      redirect_to :back
    else
      flash[:alert] = "Comment is needed!"
      redirect_to :back
    end
  end

  private
    def new_post
     params.require(:post).permit(:title, :category, :content, :user_id)
   end

   def new_comment
     params.require(:comment).permit(:comment, :user_id, :post_id)
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container">
  <ul class="collection">
    <li class="collection-item" id="new-post">
      <form action="/posts/<%= @post.id %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="text" name="post[title]" value="<%= @post.title %>"/>
        <select class="browser-default" id="category" name="post[category]">
          <option value="" disabled selected>Add Category</option>
          <option value="Mental Health">Mental Health</option>
          <option value="Psychology">Psychology</option>
          <option value="Anxiety disorder">Anxiety disorder</option>
          <option value="Depression">Depression</option>
          <option value="Schizophrenia">Schizophrenia</option>
          <option value="Suicide Prevention">Suicide Prevention</option>
          <option value="Autism Spectrum">Autism Spectrum</option>
          <option value="Eating Disorder">Eating Disorder</option>
          <option value="Other">Other</option>
      </select>
        <textarea class="materialize-textarea" name="post[content]"><%= @post.content %></textarea>
        <input type="hidden" value="<%= current_user.id %>" name="post[user_id]">
        <button type="submit" class="waves-effect waves-light btn">Update Post</button>
         Last Updated On: <%= @post.updated_at.strftime("%m-%d-%Y") %>
      </form>
    </li>
  </ul>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="collection" id="posts">
    <a href="<%= new_post_path %>" class="collection-item">Add New Article</a>
    <a href="#!" class="collection-item">My Articles</a>
  </div>
  <div class="container">
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag 'Search', name: nil, class: "waves-effect waves-light btn", placeholder: "Username"  %>
    <% end %> <br><br><br>
    <ul class="collection">
      <% @post.each do |post| %>
      <li class="collection-item avatar">
        <i class="material-icons circle">chat</i>
        <span class="title"><a href="posts/<%= post.posts_id %>"><%= post.title %></a></span>
        <p>~ <%= post.category %><br>
          By: <a href="/users/<%= post.users_id %>"><%= post.username %></a>
        </p>
        <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <ul class="collection">
    <li class="collection-item" id="new-post">
      <form action="/posts" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="text" name="post[title]" placeholder="Title *"/>
        <select class="browser-default" id="category" name="post[category]">
          <option value="" disabled selected>Add Category</option>
          <option value="Mental Health">Mental Health</option>
          <option value="Psychology">Psychology</option>
          <option value="Anxiety disorder">Anxiety disorder</option>
          <option value="Depression">Depression</option>
          <option value="Schizophrenia">Schizophrenia</option>
          <option value="Suicide Prevention">Suicide Prevention</option>
          <option value="Autism Spectrum">Autism Spectrum</option>
          <option value="Eating Disorder">Eating Disorder</option>
          <option value="Other">Other</option>
      </select>
        <textarea class="materialize-textarea" name="post[content]" placeholder="Content *"></textarea>
        <input type="hidden" value="<%= current_user.id %>" name="post[user_id]">
        <button type="submit" class="waves-effect waves-light btn">Add Post</button>
      </form>
    </li>
  </ul>
</div>

app/views/posts/show.html.erb
<div class="container">
  <ul class="collection">
    <li class="collection-item" id="show-post">
      <% if current_user.id == @post.user.id %>
      <%= link_to 'Edit Post', edit_post_path %> |
      <%= link_to "Delete Post", { controller: :posts, action: :destroy, id: @post.id }, data: { confirm: "Are you sure you want to delete?" }, method: :delete %>
      <% end %>
        <h5><%= @post.title %></h5>
        <h6>- <%= @post.category %></h6><br>
        <hr>
        <h6><%= @post.content %></h6>
        <input type="hidden" value="<%= current_user.id %>" name="post[user_id]">
        <br>
        <h6>By: <a href="/users/<%= @post.user.id %>"><%= @post.user.username %></a> on <%= @post.created_at.strftime("%m-%d-%Y") %></h6>
    </li>
  </ul>
  <u><a id="addComment">Add Comment</a></u>
  <u><%= link_to "Go Back", posts_path %></u>
</div>
<div class="container">
  <ul class="collection" id="comment-box">
    <li class="collection-item">
      <form action="/posts/addcomment" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="text" placeholder="Comment" name="comment[comment]"/>
      <input type="hidden" value="<%= current_user.id %>" name="comment[user_id]">
      <input type="hidden" value="<%= @post.id %>" name="comment[post_id]">
      <button type="submit" class="waves-effect waves-light btn">Add Comment</button><br>
      </form>
    </li>
  </ul>
    <% @comment.each do |comment| %>
    <div id="comments">
      <%= comment.comment %>
      <hr>
    </div>
    <% end %>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>