config/routes.rb
Rails.application.routes.draw do

  root 'mains#index'

  get '/search' => 'search#index'

  post '/posts/addcomment' =>'posts#addcomment'

  resources :moods
  resources :posts

  devise_for :users
    devise_scope :user do
    get '/users/:id' => 'users/registrations#show'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Katsu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <div class="nav-wrapper">
    <a href="/moods" class="brand-logo">
      <% if current_page?(posts_path) %>
        Katsu Articles ブログ
      <% else %>
          Katsu カツ
      <% end %>
    </a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if current_user.present? %>
        <li><a href="/search"><i class="material-icons">search</i></a></li>
        <li><%= link_to "Articles", posts_path %></li>
        <li><a href="/users/<%= current_user.id %>">My Chart</a></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <%else%>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
    <% end %>
  </ul>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>